Add / hookup makefiles for utils
This commit adds / modifies Makefiles to make it possible to build
various bits under utils. This commit does not yet include make install
support (that will follow in another patch).

Signed-off-by: Hans de Goede <hdegoede@redhat.com>

diff --git a/utils/xc3028-firmware/Makefile b/utils/xc3028-firmware/Makefile
--- a/utils/xc3028-firmware/Makefile
+++ b/utils/xc3028-firmware/Makefile
@@ -1,18 +1,16 @@
-# Makefile for linuxtv.org v4l2-apps/util/xc3028-firmware
+TARGETS = firmware-tool
 
-CPPFLAGS += -I../../include
-
-binaries = firmware-tool
-
-.PHONY: all clean install qv4l2
-
-all: $(binaries)
-
-clean::
-	rm -f $(binaries)
+all: $(TARGETS)
 
 firmware-tool: firmware-tool.o standards.o
-	$(CC) $^ -o $@
+	$(CC) $(LDFLAGS) -o $@ $^
+
+sync-with-kernel:
+	@if [ ! -f $(KERNEL_DIR)/drivers/media/common/tuners/tuner-xc2028-types.h ]; then \
+	  echo "Error you must set KERNEL_DIR to point to an extracted kernel source dir"; \
+	  exit 1; \
+	fi
+	cp -a $(KERNEL_DIR)/drivers/media/common/tuners/tuner-xc2028-types.h .
 
 install:
 
